eureka:
  client:
    service-url:
      defaultZone: http://www.mll.com:8761/eureka/

spring:
  application:
    name: order
  druid:
    url: jdbc:mysql:///meilele?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    maxActive: 30
    minIdle: 5
    maxWait: 10000
  rabbitmq:
    username: cheney
    password: cheney
    connection-timeout: 6000
    addresses: 192.168.1.103:5672
    virtual-host: /cheney
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true


server:
  port: 9000
  max-http-header-size: 20480

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml

#Feign
#admin:
#  ribbon:
#    ConnectTimeout: 3000
#    ReadTimeout: 60000
#    listOfServers: 192.168.1.171:9001
